name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
          ACCESS_TOKEN: ${{ secrets.CICD_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/ang-website
          BUILD_SCRIPT: npm install && ng build –output-path docs –base-href /sff_2023/ && cp docs/index.html docs/404.html
          
permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
